### ISSUE TITLE
Instaparse example

### ISSUE THREAD

**Issue by maacl** [cerner/clara-examples#4]
This is a great example of the power of both instaparse and Clara. 

Have you given any thought to how one could support end-user authoring of the DSL? It would be very cool if one could use the parser/grammar to somehow support structured editing where all possible options are shown to the user.

**Comment by rbrush** [comment]
Hi Martin,

I think this is entirely possible, but it's not clear to me that Instaparse offers enough introspection of the grammar to build an editor on top of it. (I'm not an Instaparse export, though.) I definitely think there is value in exploring this.

We do have some other options to consider as well. One is to have Instaparse convert the grammar into a simple, intermediate structure that we could easily manipulate with code (and build an editor to do so). I posted some thoughts on this in the Clara Google Group:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/clara-rules/ME7CKVdBMqg/jvCjd-khCgAJ

Would it be alright if we moved any follow up conversations over to that group? It seems like a better fit than issues. (I had neglected to link to that group in the blog post, but I have addressed that now.)

Hopefully this makes sense!

-Ryan

**Comment by maacl** [comment]
Ryan,

Thanks. Happy to move this to the Google group. Looks like Alan is already
working on something similar.

Martin

**Comment by WilliamParker** [comment]
@rbrush it looks like you added an Instaparse example at https://github.com/cerner/clara-examples/commit/d38c62f43a5b940456ae0885b520c63acd060ee6#diff-4c2f6550719134ad3e82a5510b6ff83d a couple weeks after this issue was logged.  Do you see anything left to do here or can this issue be closed?

**Comment by rbrush** [comment]
No, I think we're good. I'll close this and we can open a new issue if anything more comes up.
